-- Up Migration

CREATE TABLE consent_logs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  website_id UUID NOT NULL REFERENCES websites(id) ON DELETE CASCADE,
  website_version_id UUID NOT NULL REFERENCES website_versions(id) ON DELETE CASCADE,
  anonymous_id UUID NOT NULL, -- Random ID generated by client linked to cookie
  preferences JSONB NOT NULL, -- e.g. { "analytics": true, "marketing": false }
  user_agent TEXT,
  ip_address TEXT,
  country_code CHAR(2),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Index for fast lookup by user (anonymous_id)
CREATE INDEX idx_consent_logs_anonymous_id ON consent_logs(anonymous_id);

-- Index for reporting/analytics by website
CREATE INDEX idx_consent_logs_website_id ON consent_logs(website_id);

-- Down Migration
DROP TABLE consent_logs;
